name: datingapp
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.0
  flutter_screenutil: ^5.9.0
  url_strategy: ^0.2.0
  dio: ^5.3.3
  go_router: ^11.0.0
  fluttertoast: ^8.2.2
  loading_indicator: ^3.1.1
  rxdart: ^0.27.7
  freezed_annotation: ^2.4.1
  http: ^1.1.0
  modal_bottom_sheet: ^2.1.2
  carousel_indicator: ^1.0.6
  carousel_slider: ^4.2.1
  shared_preferences: ^2.2.2
  grouped_list: ^5.1.2
  provider: ^6.0.5
  dropdown_plus_plus: ^0.1.0+3
  image_picker: ^1.0.4
  multi_image_picker: ^4.8.01
  flutter_slidable: ^3.0.0
  popover: ^0.2.8+2
  table_calendar: ^3.0.9
  flutter_calendar_carousel: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true
  
  assets:
  - assets/
  - assets/images/
  - assets/images/button/
  - assets/images/icon/
  - assets/images/navbar_icon/
